### ISSUE TITLE
Shouldn't all the tags be structs instead of classes?

### ISSUE THREAD

**Issue by Evertt** [sahandnayebaziz/Hypertext#15]
I believe in this case they should be value types, because they don't have identity. Do you agree?

**Comment by sahandnayebaziz** [comment]
@Evertt, I too thought the same thing. When I started, I was trying to make each tag a struct that conformed to a protocol `tag`, but I hit a snag when it came to the behavior of `setChildren`.

I am today very happy with the way subclassing a tag and setting a tag's children look and work.

For creating a tag, I think these are great...
```swift
public class div : tag {}

public class img : tag { 
  override public var isSelfClosing: Bool { 
    return true 
  } 
}
```

and for setting a tag's children, I have been and remain very happy with...
```swift 
head { title { "hello world." } }
``` 

If we can keep switch to structs and keep subclassing a tag and setting a tag's children such that we look at it and like how it works and like how it looks, I'm all for it :) But I had trouble myself and switched to classes for being able to subclass `tag` and overriding a stored function `setChildren`.

**Comment by Evertt** [comment]
Sounds like a good argument. Maybe I'll try it myself and see if I can get it to work and to work as beautifully as it works now. But I guess I'll hit the same snag you did.

**Comment by sahandnayebaziz** [comment]
I'm totally with you though. I had the same thought.

**Comment by sahandnayebaziz** [comment]
I'm looking at the Swift Language Guide and it looks like maybe our feelings to use structs aren't so good, and in fact classes make more sense. 

There's a line that says:

> As a general guideline, consider creating a structure when one or more of these conditions apply:
> ...
>   - The structure does not need to inherit properties or behavior from another existing type.

And there is a little bit of behavior we want every tag to inherit, so maybe classes are totally fine.

**Comment by sahandnayebaziz** [comment]
I'm going to close this for now. Happy to discuss again if anything new comes up :)
