### ISSUE TITLE
How to catch button tap event

### ISSUE THREAD

**Issue by dickwu** [sahandnayebaziz/Hypertext#21]
use js ?

**Comment by sahandnayebaziz** [comment]
Yes! You can include Javascript in the tag elements. For a simple case like listening for a button tap...

```swift

let javascriptCode = "function myFunction() { console.log('hello world.'); }"
let scriptTag = script { javascriptCode }
let buttonElement = button(["onclick": "myFunction()"]) { "Click me" }

body { [scriptTag, buttonElement] }.render(startingWithSpaces: 0, indentingWithSpaces: 2)
```

The output of that `render()` will be...

```html
<body>
  <script>
    function myFunction() { console.log('hello world.'); }
  </script>
  <button onclick="myFunction()">
    Click me
  </button>
</body>
```

For more complicated javascript, you might need a better set up to manage all of the javascript, but rendering the HTML will be the same 😊

**Comment by dickwu** [comment]
How to use swift local function

**Comment by dickwu** [comment]
I think we need a js framework  bridge to bind web action with Swift local function

**Comment by sahandnayebaziz** [comment]
@dickwu Ah I see. You mean how do you run swift code, following a button tap on the browser? Generally speaking, what are you trying to do?

Depending on what you are trying to do, you might use [Vapor](https://github.com/vapor/vapor) and set up a route that, when receiving an `HTTP` request, runs Swift code on your server and then sends a response. There is currently no way that I know of to run Swift directly in the browser, but depending on what you are trying to do I can better describe why or why not.

**Comment by dickwu** [comment]
I have used Vapor,but I like you way to write HTML if you solve this problem, this project will become a complete web framework with network api [https://swift.org/server-apis/](url)

**Comment by sahandnayebaziz** [comment]
Ah I see! I'm glad you like this way of writing HTML :)

I'm going to create a repository with a few different samples using Vapor, Perfect, etc with Hypertext. I'll watch what happens with the server-apis :)

**Comment by sahandnayebaziz** [comment]
Closing this issue for now :)
