### ISSUE TITLE
Add library to CocoaPods

### ISSUE THREAD

**Issue by candostdagdeviren** [sahandnayebaziz/Hypertext#24]
Hello,
Thanks for creating this library. If we can use this package also with CocoaPods, it would be really great! I have an iOS project which I'm using CocoaPods as a dependency manager in it and I think CocoaPods can increase the usage of the library :)
Cheers

**Comment by sahandnayebaziz** [comment]
Good idea @candostdagdeviren. I'll take care of this later today :)

**Comment by candostdagdeviren** [comment]
@sahandnayebaziz thx for quick and positive response! Really looking forward to see it in CocoaPods :)

**Comment by sahandnayebaziz** [comment]
@candostdagdeviren https://cocoapods.org/pods/Hypertext :)
