### ISSUE TITLE
CocoaPods installation fails

### ISSUE THREAD

**Issue by candostdagdeviren** [sahandnayebaziz/Hypertext#26]
Hello again,

Thanks for the quick response. Good work! I've just tried to install the library via CocoaPods with 
`pod 'Hypertext'`in Podfile but it failed with error:

> [!] Unable to find a specification for 'Hypertext'

I also tried with installing via 
`pod 'Hypertext', :git => 'git@github.com:sahandnayebaziz/Hypertext.git', :tag => '2.1.0'`
but still same. I think something is wrong with CocoaPods. You may need to delete the repo from CocoaPods and upload it again. There are some way on the web to solve this.

Also, it would be perfect for beginners to have an installation guide for the library on Readme. This is just a suggestion to attract more people in every experience level to library :)

**Comment by sahandnayebaziz** [comment]
Hey, make sure to run `pod repo update master`. 

I just tried installing Hypertext onto a new project, with the following in the Podfile, and it worked great!

```ruby
platform :osx, '10.12'

target 'test' do
  pod 'Hypertext', '~> 2.1'
  use_frameworks!
end
```

**Comment by candostdagdeviren** [comment]
Oh, I'm still not used to update pod repo :) It's working thanks!
