### ISSUE TITLE
Ambiguous use of 'description'

### ISSUE THREAD

**Issue by briancprice** [sahandnayebaziz/Hypertext#27]
`cells.append(td([AttributeName.colspan: 2.description]) { totalLabel() })`

I'm getting errors "Ambiguous use of 'description' after Xcode was upgraded to version 9.0.  The above code is an example.  This seems to be caused by the following:

`public extension Renderable {
    var description: String {
        return render()
    }
}

extension String: Renderable {}
extension Int: Renderable {}
extension Double: Renderable {}
extension Float: Renderable {}`

In this case, Int already has a description property but since it is Renderable it is redefined.  I don't know why this wasn't an issue in Xcode 8.x.

**Comment by sahandnayebaziz** [comment]
Huh. Thank you for pointing this out. I will look at this today :)

**Comment by sahandnayebaziz** [comment]
2.1.1 has been published to CocoaPods! :)
