### ISSUE TITLE
I would like more (intuitive) instantiation options

### ISSUE THREAD

**Issue by Evertt** [sahandnayebaziz/Hypertext#8]
I made a branch locally where I changed the `init()` methods to make it more intuitive, imo. You see when you write HTML, you always write the attributes of an element first (optionally of course) and then you write that element's children.

```html
<div class="container">
  <p>
    Well hello there...
  </p>
</div>
```

But right now this library doesn't reflect that, because this library requires you to first write the children and then write the attributes, like so:

```swift
let view = div(setChildren: { p { "Well hello there..." } }, attributes: ["class": "container"])
```

My new `init()` methods allow you to do this:

```swift
let view = div(["class":"container"]) {
  p {
    "Well hello there..."
  }
}
```

Do you see how much better that reflects the actual HTML code? Would you like that too?

**Comment by Evertt** [comment]
Cool, happy you like it. My new init() method is dependent on #6 being merged though, just so you know. O:-)

**Comment by sahandnayebaziz** [comment]
@Evertt absolutely, I see how much better that is. Even if only to get the closure at the end of the function signature. This is totally great. 

I think the current order is only there because that's the order that I implemented them in :)

**Comment by sahandnayebaziz** [comment]
I've created a 2.0 milestone since #6 and this and others break any existing code that might have existed in the few hours this package has been up :) 

After we round these out, I'll release them all as 2.0.0!
